AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  se-firds-app

  Template for se-firds-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  FirdsToCsvFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./firds_to_csv
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 600
      MemorySize: 1024
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /firds
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FirdsToCsvApi:
    Description: "API Gateway endpoint URL for Prod stage for Firds function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FirdsToCsvFunction:
    Description: "Firds Lambda Function ARN"
    Value: !GetAtt FirdsToCsvFunction.Arn
  FirdsToCsvFunctionIamRole:
    Description: "Implicit IAM Role created for Firds function"
    Value: !GetAtt FirdsToCsvFunctionRole.Arn
