on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8" # update also in template.yaml->Runtime
      - name: Install Pip Dependencies for CI
        run: |
          pip3 install pytest pandas requests lxml fsspec s3fs boto3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # sam build 
      - run: sam build --use-container

      # Run Unit tests 
      - run: python3 -m pytest

      # sam deploy
      - run: sam deploy